apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: java-app
  name: java-app
  namespace: default
spec:
  progressDeadlineSeconds: 180
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: java-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      # - env:
      #   - name: spring.datasource.hikari.minimum-idle
      #     value: "5"

      - image: obachimex/app:latest
       imagePullPolicy: IfNotPresent
       livenessProbe:
         failureThreshold: 5
         httpGet:
           path: /
           port: 8080
             scheme: HTTP
           initialDelaySeconds: 120
           periodSeconds: 30
           successThreshold: 1
           timeoutSeconds: 10
         name: java-app
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 500Mi
      dnsPolicy: Default
      # imagePullSecrets:
      # - name: acrsecret
      restartPolicy: Always


